server:
  port: 8082

spring:
  application:
    name: analysis-com.integral.service
  datasource:
    url: jdbc:postgresql://localhost:5432/storing_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Soadsvanpjz228123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER:user}
    password: ${RABBITMQ_DEFAULT_PASS:Soadsvanpjz228123}

# Настройки MinIO (те же, что и в storing)
minio:
  url: http://localhost:9000
  accessKey: ${MINIO_ROOT_USER:admin}
  secretKey: ${MINIO_ROOT_PASSWORD:Soadsvanpjz228123}
  bucketName: student-works

app:
  rabbit:
    queue: works-queue
    exchange: works-exchange
    routing-key: works.routing.key
  external-api:
    word-cloud-url: https://quickchart.io/wordcloud

# Настройки внешней интеграции
external-api:
  word-cloud-url: https://quickchart.io/wordcloud

springdoc:
  swagger-ui:
    servers-url: http://localhost:8080
  api-docs:
    path: /v3/api-docs
    use-management-port: false