server:
  port: 8081

spring:
  application:
    name: storing-com.integral.service

  # Настройка БД
  datasource:
    url: jdbc:postgresql://localhost:5432/storing_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Soadsvanpjz228123}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  # Настройка RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_DEFAULT_USER}
    password: ${RABBITMQ_DEFAULT_PASS}

# Кастомные настройки для MinIO
minio:
  url: http://localhost:9000
  accessKey: ${MINIO_ROOT_USER:admin}
  secretKey: ${MINIO_ROOT_PASSWORD:Soadsvanpjz228123}
  bucket: student-works

# Настройки очередей (для удобства в коде)
app:
  rabbit:
    exchange: "work-exchange"
    queue: "analysis-queue"
    routing-key: "work.uploaded"

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs