server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # 1. Маршрут для получения отчетов (Проверяется первым)
        - id: analysis-service
          uri: http://analysis-service:8082
          predicates:
            - Path=/reports/**

        # 2. Маршруты для хранения и загрузки работ
        - id: storing-service
          uri: http://storing-service:8081
          predicates:
            - Path=/upload, /works/**, /swagger-ui/**, /v3/api-docs/**

  servlet:
    multipart:
      enabled: true
      max-file-size: 25MB
      max-request-size: 25MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs