server:
  port: 8080

spring:
  application:
    name: gateway-com.integral.service
  cloud:
    gateway:
      routes:
        # Маршрут для загрузки работ
        - id: storing-route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/works/**

        # Маршрут для получения отчетов
        - id: analysis-route
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/reports/**
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs